### ISSUE TITLE
Can't run this component: "Cannot read property 'number' of undefined"

### ISSUE THREAD

**Issue by macabeus** [loonkwil/ReactBoard#1]
I just added this package on my `dependencies`, and made a copy-paste of the example code on my project, and, when I tried to run it, I receive this error message:

**TypeError: Cannot read property 'number' of undefined**
_(anonymous function)
node_modules/react-board/dist/ReactBoard.js:420_
```
  417 | }(_react2.default.Component);
  418 | 
  419 | ReactBoardCell.propTypes = {
> 420 |     row: _react2.default.PropTypes.number.isRequired,
  421 |     col: _react2.default.PropTypes.number.isRequired,
  422 |     value: function value(props, propName) {
  423 |         var value = props[propName];
```

I'm a beginner about React and JS, then I don't know how to fix it.

I'm using the last version of React, `^16.2.0`.

**Comment by loonkwil** [comment]
Hi, I fixed this. Please update to v1.1.0.
